# Generated by Django 5.0.3 on 2024-03-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zyraapp', '0002_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
